package com.zenithblue.sambas3.input

import android.view.KeyEvent

/** Friendly labels for the normal Controls UI; Android constants stay in diagnostics. */
object PhysicalInputLabelFormatter {
    fun key(keyCode: Int?): String = keyCode?.let { code ->
        when (code) {
            KeyEvent.KEYCODE_DPAD_UP -> "Up"
            KeyEvent.KEYCODE_DPAD_DOWN -> "Down"
            KeyEvent.KEYCODE_DPAD_LEFT -> "Left"
            KeyEvent.KEYCODE_DPAD_RIGHT -> "Right"
            KeyEvent.KEYCODE_BUTTON_A -> "A"
            KeyEvent.KEYCODE_BUTTON_B -> "B"
            KeyEvent.KEYCODE_BUTTON_X -> "X"
            KeyEvent.KEYCODE_BUTTON_Y -> "Y"
            KeyEvent.KEYCODE_BUTTON_L1 -> "L1"
            KeyEvent.KEYCODE_BUTTON_R1 -> "R1"
            KeyEvent.KEYCODE_BUTTON_L2 -> "L2"
            KeyEvent.KEYCODE_BUTTON_R2 -> "R2"
            KeyEvent.KEYCODE_BUTTON_THUMBL -> "L3"
            KeyEvent.KEYCODE_BUTTON_THUMBR -> "R3"
            KeyEvent.KEYCODE_BUTTON_START -> "Start"
            KeyEvent.KEYCODE_BUTTON_SELECT -> "Select"
            KeyEvent.KEYCODE_BUTTON_MODE -> "Guide"
            KeyEvent.KEYCODE_HOME -> "Home"
            KeyEvent.KEYCODE_F1 -> "F1"
            KeyEvent.KEYCODE_F2 -> "F2"
            KeyEvent.KEYCODE_ENTER -> "Enter"
            KeyEvent.KEYCODE_TAB -> "Tab"
            KeyEvent.KEYCODE_ESCAPE -> "Esc"
            KeyEvent.KEYCODE_SPACE -> "Space"
            KeyEvent.KEYCODE_SHIFT_LEFT -> "Left Shift"
            KeyEvent.KEYCODE_SHIFT_RIGHT -> "Right Shift"
            KeyEvent.KEYCODE_NUMPAD_0 -> "Num 0"
            KeyEvent.KEYCODE_NUMPAD_1 -> "Num 1"
            KeyEvent.KEYCODE_NUMPAD_2 -> "Num 2"
            KeyEvent.KEYCODE_NUMPAD_3 -> "Num 3"
            KeyEvent.KEYCODE_NUMPAD_4 -> "Num 4"
            KeyEvent.KEYCODE_NUMPAD_5 -> "Num 5"
            KeyEvent.KEYCODE_NUMPAD_6 -> "Num 6"
            KeyEvent.KEYCODE_NUMPAD_7 -> "Num 7"
            KeyEvent.KEYCODE_NUMPAD_8 -> "Num 8"
            KeyEvent.KEYCODE_NUMPAD_9 -> "Num 9"
            else -> KeyEvent.keyCodeToString(code)
                .removePrefix("KEYCODE_")
                .replace('_', ' ')
                .lowercase()
                .replaceFirstChar { it.uppercase() }
        }
    } ?: "Unassigned"
}

/** Maps physical Android keyboard codes to the SVG KeyboardEvent.code names. */
object KeyboardKeyVisualRegistry {
    fun hotspotForKey(keyCode: Int): String? = when (keyCode) {
        KeyEvent.KEYCODE_ESCAPE -> "Escape"
        KeyEvent.KEYCODE_F1 -> "F1"
        KeyEvent.KEYCODE_F2 -> "F2"
        KeyEvent.KEYCODE_F3 -> "F3"
        KeyEvent.KEYCODE_F4 -> "F4"
        KeyEvent.KEYCODE_F5 -> "F5"
        KeyEvent.KEYCODE_F6 -> "F6"
        KeyEvent.KEYCODE_F7 -> "F7"
        KeyEvent.KEYCODE_F8 -> "F8"
        KeyEvent.KEYCODE_F9 -> "F9"
        KeyEvent.KEYCODE_F10 -> "F10"
        KeyEvent.KEYCODE_F11 -> "F11"
        KeyEvent.KEYCODE_F12 -> "F12"
        KeyEvent.KEYCODE_GRAVE -> "Backquote"
        KeyEvent.KEYCODE_1 -> "Digit1"
        KeyEvent.KEYCODE_2 -> "Digit2"
        KeyEvent.KEYCODE_3 -> "Digit3"
        KeyEvent.KEYCODE_4 -> "Digit4"
        KeyEvent.KEYCODE_5 -> "Digit5"
        KeyEvent.KEYCODE_6 -> "Digit6"
        KeyEvent.KEYCODE_7 -> "Digit7"
        KeyEvent.KEYCODE_8 -> "Digit8"
        KeyEvent.KEYCODE_9 -> "Digit9"
        KeyEvent.KEYCODE_0 -> "Digit0"
        KeyEvent.KEYCODE_MINUS -> "Minus"
        KeyEvent.KEYCODE_EQUALS -> "Equal"
        KeyEvent.KEYCODE_DEL -> "Backspace"
        KeyEvent.KEYCODE_TAB -> "Tab"
        KeyEvent.KEYCODE_Q -> "KeyQ"
        KeyEvent.KEYCODE_W -> "KeyW"
        KeyEvent.KEYCODE_E -> "KeyE"
        KeyEvent.KEYCODE_R -> "KeyR"
        KeyEvent.KEYCODE_T -> "KeyT"
        KeyEvent.KEYCODE_Y -> "KeyY"
        KeyEvent.KEYCODE_U -> "KeyU"
        KeyEvent.KEYCODE_I -> "KeyI"
        KeyEvent.KEYCODE_O -> "KeyO"
        KeyEvent.KEYCODE_P -> "KeyP"
        KeyEvent.KEYCODE_LEFT_BRACKET -> "BracketLeft"
        KeyEvent.KEYCODE_RIGHT_BRACKET -> "BracketRight"
        KeyEvent.KEYCODE_BACKSLASH -> "Backslash"
        KeyEvent.KEYCODE_CAPS_LOCK -> "CapsLock"
        KeyEvent.KEYCODE_A -> "KeyA"
        KeyEvent.KEYCODE_S -> "KeyS"
        KeyEvent.KEYCODE_D -> "KeyD"
        KeyEvent.KEYCODE_F -> "KeyF"
        KeyEvent.KEYCODE_G -> "KeyG"
        KeyEvent.KEYCODE_H -> "KeyH"
        KeyEvent.KEYCODE_J -> "KeyJ"
        KeyEvent.KEYCODE_K -> "KeyK"
        KeyEvent.KEYCODE_L -> "KeyL"
        KeyEvent.KEYCODE_SEMICOLON -> "Semicolon"
        KeyEvent.KEYCODE_APOSTROPHE -> "Quote"
        KeyEvent.KEYCODE_ENTER -> "Enter"
        KeyEvent.KEYCODE_SHIFT_LEFT -> "ShiftLeft"
        KeyEvent.KEYCODE_Z -> "KeyZ"
        KeyEvent.KEYCODE_X -> "KeyX"
        KeyEvent.KEYCODE_C -> "KeyC"
        KeyEvent.KEYCODE_V -> "KeyV"
        KeyEvent.KEYCODE_B -> "KeyB"
        KeyEvent.KEYCODE_N -> "KeyN"
        KeyEvent.KEYCODE_M -> "KeyM"
        KeyEvent.KEYCODE_COMMA -> "Comma"
        KeyEvent.KEYCODE_PERIOD -> "Period"
        KeyEvent.KEYCODE_SLASH -> "Slash"
        KeyEvent.KEYCODE_SHIFT_RIGHT -> "ShiftRight"
        KeyEvent.KEYCODE_CTRL_LEFT -> "ControlLeft"
        KeyEvent.KEYCODE_META_LEFT -> "MetaLeft"
        KeyEvent.KEYCODE_ALT_LEFT -> "AltLeft"
        KeyEvent.KEYCODE_SPACE -> "Space"
        KeyEvent.KEYCODE_ALT_RIGHT -> "AltRight"
        KeyEvent.KEYCODE_META_RIGHT -> "MetaRight"
        KeyEvent.KEYCODE_MENU -> "ContextMenu"
        KeyEvent.KEYCODE_CTRL_RIGHT -> "ControlRight"
        KeyEvent.KEYCODE_DPAD_LEFT -> "ArrowLeft"
        KeyEvent.KEYCODE_DPAD_DOWN -> "ArrowDown"
        KeyEvent.KEYCODE_DPAD_RIGHT -> "ArrowRight"
        KeyEvent.KEYCODE_DPAD_UP -> "ArrowUp"
        KeyEvent.KEYCODE_INSERT -> "Insert"
        KeyEvent.KEYCODE_MOVE_HOME -> "Home"
        KeyEvent.KEYCODE_PAGE_UP -> "PageUp"
        KeyEvent.KEYCODE_FORWARD_DEL -> "Delete"
        KeyEvent.KEYCODE_MOVE_END -> "End"
        KeyEvent.KEYCODE_PAGE_DOWN -> "PageDown"
        KeyEvent.KEYCODE_NUM_LOCK -> "NumLock"
        KeyEvent.KEYCODE_NUMPAD_DIVIDE -> "NumpadDivide"
        KeyEvent.KEYCODE_NUMPAD_MULTIPLY -> "NumpadMultiply"
        KeyEvent.KEYCODE_NUMPAD_SUBTRACT -> "NumpadSubtract"
        KeyEvent.KEYCODE_NUMPAD_ADD -> "NumpadAdd"
        KeyEvent.KEYCODE_NUMPAD_ENTER -> "NumpadEnter"
        KeyEvent.KEYCODE_NUMPAD_0 -> "Numpad0"
        KeyEvent.KEYCODE_NUMPAD_1 -> "Numpad1"
        KeyEvent.KEYCODE_NUMPAD_2 -> "Numpad2"
        KeyEvent.KEYCODE_NUMPAD_3 -> "Numpad3"
        KeyEvent.KEYCODE_NUMPAD_4 -> "Numpad4"
        KeyEvent.KEYCODE_NUMPAD_5 -> "Numpad5"
        KeyEvent.KEYCODE_NUMPAD_6 -> "Numpad6"
        KeyEvent.KEYCODE_NUMPAD_7 -> "Numpad7"
        KeyEvent.KEYCODE_NUMPAD_8 -> "Numpad8"
        KeyEvent.KEYCODE_NUMPAD_9 -> "Numpad9"
        KeyEvent.KEYCODE_NUMPAD_DOT -> "NumpadDecimal"
        KeyEvent.KEYCODE_SCROLL_LOCK -> "ScrollLock"
        KeyEvent.KEYCODE_BREAK -> "Pause"
        else -> null
    }
}
